### ISSUE TITLE
Local Images Popup

### ISSUE THREAD

**Issue by blackvitriol** [r-spatial/leafpop#1]
Good day team Leafpop,
I have to begin with commendation, as this library is very useful for me and it is a great library on top of Leaflet. Thank you very much for development on this.

For using local images in popups, I cannot understand how to deal with the temp files/folder.
I am using files places in www/images/ but I cannot refer to them in:
_popup = popupImage(img,src="local")_

Getting this error:
`Failed to load resource: the server responded with a status of 404 (Not Found)`

**Comment by tim-salabim** [comment]
Thanks! The issue is that the images are currently saved in a non-htmlwidget-compatible folder location which only works for an interactive R session (i.e. not when the map is saved via `saveWidget`). I will address this soon, as this is a long standing issue.

**Comment by tim-salabim** [comment]
@blackvitriol I think we need to re-design the functionality if we want to make sure that things will work not only in an interactive session. To register the local images with the leaflet widget, we need to have access to the `map` object which we currently don't have. Therefore, I propose to redesign the function as follows:

```r
leaflet() %>%
  addTiles() %>%
  addCircleMarkers(data = breweries[1:2, ], group = "brew") %>%
  addImagePopup(images, group = "brew")
```
Basically, we don't call the `popup` argument in `addCircleMaekers` to pass the popup content, but have a dedicated `add*` function that will add the content of `images` to each feature of the `group` layer. 

Would this be acceptable for you? I don't see any other way, as we currently cannot know where the leaflet map object is located in `tempfolder()`. We can, however, register the image folder as a dependency when we have access to the map object.

**Comment by blackvitriol** [comment]
I don't know if adding images to the group layer will have the intended effect.
Maybe we should look at https://github.com/rstudio/leaflet to find out where the map object is created, or directly reference ($map) it in non-interactive sessions.

**Comment by tim-salabim** [comment]
I don't understand what you mean?

**Comment by tim-salabim** [comment]
@blackvitriol the latest commit exposes 2 new functions `addPopupImages` and `addPopupGraphs` which properly register the supplied images/graphs with the map object. This means that images & graphs (images as well actually) should now always be included, even in markdown documents or when the map is saved locally. See the examples and or README on how they work.
Hope this is the desired behaviour. In case it is not, don't hesitate to re-open this issue.
