### ISSUE TITLE
Can't add multiple popup images to addPopupImages from local source

### ISSUE THREAD

**Issue by dalgroundwater** [r-spatial/leafpop#19]
I am trying to add two images to a **single** popup point using the "addPopupImages" function for a leaflet map from images on my local computer.

Every time I try and add two images such as:

image <- c("DJI_0046.JPG", "DJI_0044.JPG")

and then use this line in the leaflet map:

addPopupImages(image, group="photo_1", width = 300) 

Only the first image pops up (not both). Is it possible to add multiple photos to a single popup point? Thanks!

**Here is my code:**

image <- c("DJI_0046.JPG", "DJI_0044.JPG")

map = leaflet() %>%
  addProviderTiles("Esri.WorldImagery") %>%
  addCircleMarkers(lng=-60.96074, lat=46.67232, group="photo_1", radius = 6, color = 'black', fillColor = '#FFA000', weight = 1, 
      fillOpacity = .8) %>%
  addPopupImages(image, group="photo_1", width = 300) 

map

**Comment by tim-salabim** [comment]
No, this is not possible currently. How about using the `magick` package to bind the two images together before adding them to to the map? I've not used `magick` much, but it sounds like something that should be easy with `magick`

**Comment by tim-salabim** [comment]
What you can do now is call `addPopupImages` twice for the same layer:

```r
library(leaflet)
library(sf)
library(lattice)

pnt = st_as_sf(data.frame(x = 174.764474, y = -36.877245),
               coords = c("x", "y"),
               crs = 4326)

img1 = "http://bit.ly/1TVwRiR"
img2 = "https://www.r-project.org/logo/Rlogo.png"

leaflet() %>%
  addTiles() %>%
  addCircleMarkers(data = pnt, group = "pnt") %>%
  addPopupImages(img1, group = "pnt", width = 300, maxWidth = 300) %>%
  addPopupImages(img2, group = "pnt", width = 300, maxWidth = 300)
```
![image](https://user-images.githubusercontent.com/2826432/119220499-1f4aaa80-baeb-11eb-8b95-4bbd9822a0c0.png)

Note that the `maxWidth` specification is only needed to prevent the images being rendered side-by-side. They will be rendered side-by-side by default as long as the combined width is less than 2000px.

I am closing this here, as I think this is solved
