### ISSUE TITLE
Plotly graph causes strange error message in popup in leaflet

### ISSUE THREAD

**Issue by cschwarz-stat-sfu-ca** [r-spatial/leafpop#20]
I'm trying to use graphs generated by plotly for popups, but when I try the code below I get the error message:

      /chunk_output/ED3D3A09EC52D318/952E30A8/popup_graphs/tmp_1.html not found

It is possible to embed htmlwidgets as popups?
https://github.com/rstudio/leaflet/issues/376 has a similar question and the answers refer to mapvew.
When I try the example from 2017 where a datatable widget is used in a popup it also returns with a similar error message

Here is MWE Running on a Mac, Big Sur 11.2.1; R 4.0.4; latest version of packages from CRAN...

Thanks in advance...
Carl Schwarz

```
#------------------------------------------
# try with a plot_ly object - DOES NOT WORK
df <- read.csv(textConnection(
  "Name,Lat,Long
  Samurai Noodle,47.597131,-122.327298"
))

p <- plot_ly(data=data.frame(x=1:10, y=rnorm(10)), x=~x, y=~y, type="scatter") 
p <- list(p)


leaflet(df) %>% addTiles() %>%
  addMarkers(
    ~Long, ~Lat, group="3", popup=popupGraph(graph=p, type="html"))
```

**Comment by tim-salabim** [comment]
Hi, we have a (still unexported) function for this kind of thing - `addPopupIframes`. The following should do what you want:

```r
library(leaflet)
library(leafpop)
library(plotly)
library(htmlwidgets)

df = read.csv(textConnection(
  "Name,Lat,Long
  Samurai Noodle,47.597131,-122.327298"
))

p = plot_ly(data=data.frame(x=1:10, y=rnorm(10)), x=~x, y=~y, type="scatter") 

fl = tempfile(fileext = ".html")
saveWidget(p, file = fl)

leaflet(df) %>% addTiles() %>%
  addMarkers(
    ~Long, ~Lat, group="3"
  ) %>%
  leafpop:::addPopupIframes(
    source = fl
    , group = "3"
  )
```

![image](https://user-images.githubusercontent.com/2826432/116781793-9e693780-aa85-11eb-8e3f-0f3543fc879b.png)

**Comment by cschwarz-stat-sfu-ca** [comment]
THanks for the feedback... how about when you have a list of plotly graphs,
one for each point. Will addPopupIframe() accept a list of file names to
match against the list of points?
Carl Schwarz

**Comment by tim-salabim** [comment]
Yes it will

```r
library(leaflet)
library(leafpop)
library(plotly)
library(htmlwidgets)

df = read.csv(textConnection(
  "Name,Lat,Long
  Samurai Noodle,47.597131,-122.327298
  Another Place,47.687,-121.753"
))

p = Map(
  function(x, y) {
    df = data.frame(x = x, y = y)
    plot_ly(data=df, x=~x, y=~y, type="scatter")
  }
  , x = list(1:10, 1:10)
  , y = list(10:1, 1:10)
)

fl = lapply(
  p
  , function(j) {
    fl = tempfile(fileext = ".html")
    saveWidget(j, file = fl)
    return(fl)
  }
)

leaflet(df) %>% addTiles() %>%
  addMarkers(
    ~Long
    , ~Lat
    , group="3"
  ) %>%
  leafpop:::addPopupIframes(
    source = fl
    , group = "3"
  )
```
You can even mix local and remote (i.e. urls) content:

```r
library(leaflet)
library(leafpop)
library(plotly)
library(htmlwidgets)

df = read.csv(textConnection(
  "Name,Lat,Long
  Samurai Noodle,47.597131,-122.327298
  Another Place,47.687,-121.753
  Third Plce,47.344,-122.112"
))

p = Map(
  function(x, y) {
    df = data.frame(x = x, y = y)
    plot_ly(data=df, x=~x, y=~y, type="scatter")
  }
  , x = list(1:10, 1:10)
  , y = list(10:1, 1:10)
)

fl = lapply(
  p
  , function(j) {
    fl = tempfile(fileext = ".html")
    saveWidget(j, file = fl)
    return(fl)
  }
)
fl = append(fl, "https://www.youtube.com/embed/iApz08Bh53w?autoplay=1")

m = leaflet(df) %>% addTiles() %>%
  addMarkers(
    ~Long
    , ~Lat
    , group="3"
  ) %>%
  leafpop:::addPopupIframes(
    source = fl
    , group = "3"
  )

m
```
Note that when you want to save the map locally, you need to set `selfcontained = FALSE` in `htmlwidgets::saveWidget` or `mapview::mapshot`

```r
mapview::mapshot(m, url = "/home/timpanse/Downloads/test_iframe.html", selfcontained = FALSE)
```
And for some security reason, my browser doesn't allow to play the video in the popup unless the map is served via e.g. `localhost`.

**Comment by cschwarz-stat-sfu-ca** [comment]
Great... thanks for your help.  Carl.

**Comment by tim-salabim** [comment]
I'm closing this here. Feel free to re-open

**Comment by asadow** [comment]
Great function. Curious why is it still unexported?

**Comment by asadow** [comment]
On that note, a warning would be nice to have if the object supplied to `source` is less (or greater?) than the length of the data referenced in the group. It causes some unexpected behaviour.

**Comment by asadow** [comment]
The `position` arg would be great for this as well.
