### ISSUE TITLE
Size issue in SVG graphs

### ISSUE THREAD

**Issue by becarioprecario** [r-spatial/leafpop#25]
Hi,

I believe that the conversion factor from pixels to inches is wrong in leafpop:::popupSVGraph. I was using this function but leaflet shown about  2/3 of the image. After changing the pixel-to-inch conversion factor from 72 to 96 I get the right scale in my plots.

Best,

Virgilio

**Comment by codyevers** [comment]
I can confirm this as well. The width and height in the svg tag appear to be incorrectly tagged with 'pt' unit. I can fix the scaling issue if I manually change these units (i.e., 300pt to 300px) using Chrome's development tools. I have not been able to locate where in the code can be resolved however.

**Comment by KingaHill** [comment]
Can someone provide more detail about how to work around this issue? I am experiencing the same sizing problem with "svg" and am not sure how to adjust that conversion.

**Comment by tim-salabim** [comment]
@KingaHill Can you please try again? The above commit should fix this.

**Comment by KingaHill** [comment]
It works when I download the development version @tim-salabim. Thank you!

**Comment by tim-salabim** [comment]
Thanks, closing here then
