### ISSUE TITLE
htmlwidgets::saveWidget() doesn't work nested popup

### ISSUE THREAD

**Issue by leungi** [r-spatial/leafpop#5]
This is taken from the package example.

The resulting `html` doesn't load the content in `popupGraph()`. Is there a way to embed, say, via an `embed` argument in `popupGraph()`.

```
library(leaflet)
library(leafpop)

leaflet() %>%
  addTiles() %>%
  addCircleMarkers(
    data = breweries91[1, ],
    popup = popupGraph(
      leaflet() %>%
        addProviderTiles("Esri.WorldImagery") %>%
        addMarkers(data = breweries91[1, ],
                   popup = popupTable(breweries91[1, ])),
      type = "html"
    )
  ) %>% 
  htmlwidgets::saveWidget('pop_nested.html', selfcontained = TRUE)
```

**Comment by tim-salabim** [comment]
I am currently working on a solution (`addPopupIframes`/`addPopupWidgets`) that should make this possible. I hope to have this working soon.

**Comment by tim-salabim** [comment]
So, after ages (sorry!) here's a solution that works. Some things to note:

- `addPopupIframes` needs a file or url be passed to `source`
-  saving to local html will need `selfcontained = FALSE` (otherwise bg tiles of popup map don't show)

Still an unexported function, as I am still not happy with the general implementation.

```r
library(leaflet)
library(leafpop)
library(sp)

pop_map = leaflet() %>%
  addProviderTiles(
    "Esri.WorldImagery"
  ) %>%
  addMarkers(
    data = breweries91[1, ]
    , popup = popupTable(breweries91[1, ])
  )

fl = tempfile(fileext = ".html")
htmlwidgets::saveWidget(
  pop_map
  , file = fl
)

pop_nested = leaflet() %>%
  addTiles(group = "OSM") %>%
  addCircleMarkers(
    data = breweries91[1, ]
    , group = "brew1"
  ) %>%
  leafpop:::addPopupIframes(
    source = fl
    , group = "brew1"
  )

htmlwidgets::saveWidget(
  pop_nested
  , '/home/timpanse/Downloads/pop_nested.html'
  , selfcontained = FALSE
)
```
Closing this. If there are other requests like this one, please open a new issue.

**Comment by leungi** [comment]
No worries; thanks for the update 🙏 

Tested it and looks promising; we have a solution for now 🙌
