### ISSUE TITLE
could not find function "addPopupGraphs"

### ISSUE THREAD

**Issue by git-ashish** [r-spatial/leafpop#7]
Hello,

I am trying out the [popUpGraph](https://github.com/r-spatial/leafpop#popupgraph) example but facing an error.

```
library(sf)
library(leaflet)
library(lattice)

pnt = st_as_sf(data.frame(x = 174.764474, y = -36.877245),
                coords = c("x", "y"),
                crs = 4326)

p2 = levelplot(t(volcano), col.regions = terrain.colors(100))

leaflet() %>%
  addTiles() %>%
  addCircleMarkers(data = pnt, group = "pnt") %>%
  addPopupGraphs(list(p2), group = "pnt", width = 300, height = 400)

```
![image](https://user-images.githubusercontent.com/2697421/61171037-79919080-a58f-11e9-8d86-b359e5f305fc.png)

> Error in addPopupGraphs(., list(p2), group = "pnt", width = 300, height = 400) : 
>  could not find function "addPopupGraphs"

I was able to run the backward compatibility example though:

```
leaflet() %>%
  addTiles() %>%
  addCircleMarkers(data = pnt, popup = popupGraph(p2, width = 300, height = 400))
```

Thanks!

**Comment by tim-salabim** [comment]
Did you load leafpop via `library(leafpop)`? And did you install it from github? The `addPopup*()` functions are not on CRAN yet

**Comment by git-ashish** [comment]
Got it. Uninstalled and re-installed from Github repo `remotes::install_github("r-spatial/leafpop")`. This solved the error. Thank you!
