### ISSUE TITLE
Add table customisation options

### ISSUE THREAD

**Issue by rlh1994** [r-spatial/leafpop#9]
Hi,

Not an issue, much more a feature request. 

I think it could be really useful to be able to have some additional options for the `popupTable()` function that allows for something like striped tables (as was the default in `mapview`), bordering, etc. As I find this makes it easier for users to read a table compared to the current plain white view. 

I know very little html but it seems like adding:

```html
<style>
tr:nth-child(odd) {background-color: #f2f2f2;}
</style>
```
between the `</head>`  and `<body>` tags of `templates/popup.brew` does the trick for striped at least, and could conditionally use a different brew file (unless you can put conditions in a brew file, I have no experience with them) and the background-color could also be optional input that would need to be fed through.

Is this something you see a benefit in adding?

**Comment by tim-salabim** [comment]
@rlh1994 thanks for the suggestion. @fdetsch is currently rewriting the C++ part to use pure R (branch vectorized). We have already thought about a way to let the user supply but haven't come up with a clever solution yet. But it's on the table.

**Comment by TacticalFate** [comment]
Another feature that would be nice for users would be to be able to set a popup title - that is a title that goes above the scroll container. They could then use one column of the input data to be a title for the popup that will always be visible even if scroll is enabled and not all columns are visible. 

I acheived the following below by inserting

`glue(<div class = 'leaflet-title'><b><h4>ID# {column}</b></h4></div>")` 

after the `<body>` tag in the HTML generated by popupTable, but this could definitely be generated programatically (For the rest of the formatting I modified mapview's CSS for popups and inserted it into my shiny app)

![image](https://user-images.githubusercontent.com/46234178/74109223-a28ef980-4b4f-11ea-9aa6-61965755d476.png)

**Comment by tim-salabim** [comment]
Still struggling with finding a proper/clever way of manipulating css. Any suggestions are more than welcome!

**Comment by rlh1994** [comment]
> Still struggling with finding a proper/clever way of manipulating css. Any suggestions are more than welcome!

Still not particularly well versed in HTML/CSS but trying to work it through in the current master branch state, couldn't the `createTemplate` function be passed arguments cascaded through from the original `popupTable` call? These could then customise the text that function returns through some simple (yet long probably) if statements? Trick will be understanding how they interact and where exactly they go.

Would probably need a real think through what options you could want in total for a table, but the few already on this thread and some other common ones I can think of might be:

- Striped  rows (and colour option)
- Table title
- Maximum scroll height (and probably a default overflow:auto)
- Not sure what the current solution is as I've never had the problem, but maximum width and a default oveflow x?
- Maybe some customisation on the borders or something else?

If the arguments were just cascaded as extra arguments via `...` through `popupTable`, `brewPopupTable`, `listPopupTemplates` finally to `createTemplate` then ongoing development should be a bit easier as you'd only have to add more to the final function and just document them in the initial call. Simple example of the first and third would be something like

```r
createTemplate <- function(striped = FALSE, stripeCol = '#C0C0C0', maxHeight = NA) {
    head <- '<html><head><link rel="stylesheet" type="text/css" href="lib/popup/popup.css"></head><style>'
    
    style <- ''
    
    body <- '</style><body>'
    
    div <- ''
    
    tail <- '<table class="popup scrollable" id="popup">
    %s
    </table></div></body></html>'
                          
    if (striped) {
        style <- paste0('tr:nth-child(odd) {background-color: ',stripeCol,';}')
    }
    if (!(is.na(maxHeight))){
        div <- paste0('<div class="scrollableContainer", style ="max-height:',maxHeight,'px; overflow:auto;">')
    } 
    else {
        div <- '<div class="scrollableContainer">'
    }
                          
    gsub("\\n", "", paste(head, style, body, div, tail, sep = '\n'))
}

```
```
> createTemplate()
[1] "<html><head><link rel=\"stylesheet\" type=\"text/css\" href=\"lib/popup/popup.css\"></head><style></style><body><div class=\"scrollableContainer\"><table class=\"popup scrollable\" id=\"popup\">%s</table></div></body></html>"
> createTemplate(striped = TRUE)
[1] "<html><head><link rel=\"stylesheet\" type=\"text/css\" href=\"lib/popup/popup.css\"></head><style>tr:nth-child(odd) {background-color: #C0C0C0;}</style><body><div class=\"scrollableContainer\"><table class=\"popup scrollable\" id=\"popup\">%s</table></div></body></html>"
```

What do you think?

**Comment by tim-salabim** [comment]
That, I think, sounds like a reasonable approach. Some points to think about:

* can we come up with a function that creates a list of styles? That way we could control defaults and let the user update only what they want to change. Also we can ensure that all necessary fields are filled.
* we could then use this list to populate a `sprintf()` call with the list contents so that we don't have to use a thousand if clauses.

The `sprintf` would then somewhat mimic the original implementation using brew. With the added benefit that we can drop the **brew** dependency (not that it's hefty, but the less the better).

**Comment by rlh1994** [comment]
Maybe opens some bigger questions before diving into it:

1. Would you ever want to support a pure df/list input into the `popupTable` function, so as well as pictures and charts it would also be possible to add full tables into the pop-ups e.g. visualising the states data, with the colour being the overall presidential election result, but a popup gives a dataframe of more detailed information (maybe vote breakdown, or votes by district etc)? Even if this was maybe a separate function like `addPopupTable` it'd be worth thinking about before committing to an approach.

2. Regarding dependencies, instead of reinventing the wheel `kableExtra` (http://haozhu233.github.io/kableExtra/awesome_table_in_html.html) already has all these features and more, but it would require the additional dependency of both `kable` and `kableExtra` (including the unnecessary LaTeX parts) and I'm not entirely sure you would even allow the user to work with this that isn't horribly non user-friendly. There's also a case to be made for `formattable` but I feel that's more for in-table designs, rather than table design itself so much.

If the answer to 1 is yes, then having a more robust, separate function that just takes in a dataframe and produces the html for that as a table might be easier, then keep the conversion of the spdf into the single record df separate.
On 2 it feels like a waste to not use a package that already does this, but also feels like overkill for this, and I don't know how you would incorporate it.

**Comment by tim-salabim** [comment]
`popupTable` now has a `className` argument for using custom CSS. See [this gist](https://gist.github.com/tim-salabim/bbe1c588d0444f1c2cc90d8a8dfa6690) for an example.
